volumes:
  caddy_data:
  caddy_config:

services:
  worker: &app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: &env
      DATABASE_URL: ${DATABASE_URL}
      LEANCLOUD_API_SERVER: ${LEANCLOUD_API_SERVER}
      LEANCLOUD_APP_ID: ${LEANCLOUD_APP_ID}
      LEANCLOUD_APP_KEY: ${LEANCLOUD_APP_KEY}
      LEANCLOUD_SESSION_TOKEN: ${LEANCLOUD_SESSION_TOKEN}
      APP_ORIGIN: ${APP_ORIGIN}
      BUNNYCDN_ENDPOINT: ${BUNNYCDN_ENDPOINT}
      BUNNYCDN_ACCESS_KEY: ${BUNNYCDN_ACCESS_KEY}
      MAILER_DSN: ${MAILER_DSN}
      MONOLOG_FROM_EMAIL: ${MONOLOG_FROM_EMAIL}
      MONOLOG_TO_EMAIL: ${MONOLOG_TO_EMAIL}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: php bin/console messenger:consume -vv scheduler_default async
  web:
    <<: *app
    command: sh -c 'APP_RUNTIME=Runtime\\Swoole\\Runtime php -f public/index.php'
    environment:
      <<: *env
    healthcheck:
      test: ["CMD", "curl", "-fI", "http://localhost/"]
      timeout: 5s
      start_period: 30s
      start_interval: 1s
