#!/command/with-contenv sh
# shellcheck shell=sh

set -eux

cd /srv/app

export APP_RUNTIME=Manyou\\WorkermanSymfonyRuntime\\Runtime
export APP_RUNTIME_SOCKET=http://127.0.0.1:3000

exec 2>&1
exec s6-setuidgid www-data php -f public/index.php start
