#!/command/with-contenv sh
# shellcheck shell=sh

set -eux

cd /app

export APP_RUNTIME=Manyou\\WorkermanSymfonyRuntime\\Runtime
export APP_RUNTIME_SOCKET=http://127.0.0.1:3000
export APP_RUNTIME_LOG_FILE=/run/s6/workerman-log.fifo
export APP_RUNTIME_PID_FILE=/run/workerman/workerman.pid

exec su-exec www-data:www-data php -f public/index.php start
