#!/usr/bin/env sh

set -eux

mkdir -p \
  /var/log/nginx-access-log \
  /var/log/nginx-error-log \
  /var/cache/nginx \
  /run/nginx

touch \
  /run/s6/nginx-access-log.fifo \
  /run/s6/nginx-error-log.fifo

chown nobody:nogroup \
  /var/log/nginx-access-log \
  /var/log/nginx-error-log

chown www-data:www-data \
  /var/cache/nginx \
  /run/nginx \
  /run/s6/nginx-access-log.fifo \
  /run/s6/nginx-error-log.fifo

chmod 02755 \
  /var/log/nginx-access-log \
  /var/log/nginx-error-log \
  /var/cache/nginx \
  /run/nginx

nginx-conf app.conf open_file_cache.conf
nginx-pull-config -- su-exec www-data:www-data nginx -e /run/s6/nginx-error-log.fifo -g 'pid /run/nginx/nginx.pid;' -t

rm -rf \
  /run/s6/nginx-access-log.fifo \
  /run/s6/nginx-error-log.fifo

mkfifo -m 0600 \
  /run/s6/nginx-access-log.fifo \
  /run/s6/nginx-error-log.fifo

chown www-data:www-data \
  /run/s6/nginx-access-log.fifo \
  /run/s6/nginx-error-log.fifo
