#!/usr/bin/env sh

set -eux

dest=$1
shift

for path in "$@"; do
  if [ -f "$path" ]; then
    dir=${path%/*}
    dest_dir=${dest%/}
    [ "$dir" != "$path" ] && dest_dir="${dest}${dir}"
    mkdir -p "$dest_dir"
    cp "$path" "${dest_dir}/"
  elif [ -d "$path" ]; then
    dest_dir="${dest}${path}"
    mkdir -p "$dest_dir"
    cp -R "${path}/." "${dest_dir}/"
  else
    echo "Path not found: \"${path}\"." 1>&2
    exit 1
  fi
done
